// Code generated by go generate; DO NOT EDIT.
package cpu

const (
	NOP           OpcodeValue = 0x00
	LD_BC_d16     OpcodeValue = 0x01
	STOP_0        OpcodeValue = 0x10
	LD_DE_d16     OpcodeValue = 0x11
	LD_valDE_A    OpcodeValue = 0x12
	INC_DE        OpcodeValue = 0x13
	INC_D         OpcodeValue = 0x14
	DEC_D         OpcodeValue = 0x15
	LD_D_d8       OpcodeValue = 0x16
	RLA           OpcodeValue = 0x17
	JR_r8         OpcodeValue = 0x18
	ADD_HL_DE     OpcodeValue = 0x19
	LD_A_valDE    OpcodeValue = 0x1a
	DEC_DE        OpcodeValue = 0x1b
	INC_E         OpcodeValue = 0x1c
	DEC_E         OpcodeValue = 0x1d
	LD_E_d8       OpcodeValue = 0x1e
	RRA           OpcodeValue = 0x1f
	LD_valBC_A    OpcodeValue = 0x02
	JR_NZ_r8      OpcodeValue = 0x20
	LD_HL_d16     OpcodeValue = 0x21
	LD_valHLinc_A OpcodeValue = 0x22
	INC_HL        OpcodeValue = 0x23
	INC_H         OpcodeValue = 0x24
	DEC_H         OpcodeValue = 0x25
	LD_H_d8       OpcodeValue = 0x26
	DAA           OpcodeValue = 0x27
	JR_Z_r8       OpcodeValue = 0x28
	ADD_HL_HL     OpcodeValue = 0x29
	LD_A_valHLinc OpcodeValue = 0x2a
	DEC_HL        OpcodeValue = 0x2b
	INC_L         OpcodeValue = 0x2c
	DEC_L         OpcodeValue = 0x2d
	LD_L_d8       OpcodeValue = 0x2e
	CPL           OpcodeValue = 0x2f
	INC_BC        OpcodeValue = 0x03
	JR_NC_r8      OpcodeValue = 0x30
	LD_SP_d16     OpcodeValue = 0x31
	LD_valHLdec_A OpcodeValue = 0x32
	INC_SP        OpcodeValue = 0x33
	INC_valHL     OpcodeValue = 0x34
	DEC_valHL     OpcodeValue = 0x35
	LD_valHL_d8   OpcodeValue = 0x36
	SCF           OpcodeValue = 0x37
	JR_C_r8       OpcodeValue = 0x38
	ADD_HL_SP     OpcodeValue = 0x39
	LD_A_valHLdec OpcodeValue = 0x3a
	DEC_SP        OpcodeValue = 0x3b
	INC_A         OpcodeValue = 0x3c
	DEC_A         OpcodeValue = 0x3d
	LD_A_d8       OpcodeValue = 0x3e
	CCF           OpcodeValue = 0x3f
	INC_B         OpcodeValue = 0x04
	LD_B_B        OpcodeValue = 0x40
	LD_B_C        OpcodeValue = 0x41
	LD_B_D        OpcodeValue = 0x42
	LD_B_E        OpcodeValue = 0x43
	LD_B_H        OpcodeValue = 0x44
	LD_B_L        OpcodeValue = 0x45
	LD_B_valHL    OpcodeValue = 0x46
	LD_B_A        OpcodeValue = 0x47
	LD_C_B        OpcodeValue = 0x48
	LD_C_C        OpcodeValue = 0x49
	LD_C_D        OpcodeValue = 0x4a
	LD_C_E        OpcodeValue = 0x4b
	LD_C_H        OpcodeValue = 0x4c
	LD_C_L        OpcodeValue = 0x4d
	LD_C_valHL    OpcodeValue = 0x4e
	LD_C_A        OpcodeValue = 0x4f
	DEC_B         OpcodeValue = 0x05
	LD_D_B        OpcodeValue = 0x50
	LD_D_C        OpcodeValue = 0x51
	LD_D_D        OpcodeValue = 0x52
	LD_D_E        OpcodeValue = 0x53
	LD_D_H        OpcodeValue = 0x54
	LD_D_L        OpcodeValue = 0x55
	LD_D_valHL    OpcodeValue = 0x56
	LD_D_A        OpcodeValue = 0x57
	LD_E_B        OpcodeValue = 0x58
	LD_E_C        OpcodeValue = 0x59
	LD_E_D        OpcodeValue = 0x5a
	LD_E_E        OpcodeValue = 0x5b
	LD_E_H        OpcodeValue = 0x5c
	LD_E_L        OpcodeValue = 0x5d
	LD_E_valHL    OpcodeValue = 0x5e
	LD_E_A        OpcodeValue = 0x5f
	LD_B_d8       OpcodeValue = 0x06
	LD_H_B        OpcodeValue = 0x60
	LD_H_C        OpcodeValue = 0x61
	LD_H_D        OpcodeValue = 0x62
	LD_H_E        OpcodeValue = 0x63
	LD_H_H        OpcodeValue = 0x64
	LD_H_L        OpcodeValue = 0x65
	LD_H_valHL    OpcodeValue = 0x66
	LD_H_A        OpcodeValue = 0x67
	LD_L_B        OpcodeValue = 0x68
	LD_L_C        OpcodeValue = 0x69
	LD_L_D        OpcodeValue = 0x6a
	LD_L_E        OpcodeValue = 0x6b
	LD_L_H        OpcodeValue = 0x6c
	LD_L_L        OpcodeValue = 0x6d
	LD_L_valHL    OpcodeValue = 0x6e
	LD_L_A        OpcodeValue = 0x6f
	RLCA          OpcodeValue = 0x07
	LD_valHL_B    OpcodeValue = 0x70
	LD_valHL_C    OpcodeValue = 0x71
	LD_valHL_D    OpcodeValue = 0x72
	LD_valHL_E    OpcodeValue = 0x73
	LD_valHL_H    OpcodeValue = 0x74
	LD_valHL_L    OpcodeValue = 0x75
	HALT          OpcodeValue = 0x76
	LD_valHL_A    OpcodeValue = 0x77
	LD_A_B        OpcodeValue = 0x78
	LD_A_C        OpcodeValue = 0x79
	LD_A_D        OpcodeValue = 0x7a
	LD_A_E        OpcodeValue = 0x7b
	LD_A_H        OpcodeValue = 0x7c
	LD_A_L        OpcodeValue = 0x7d
	LD_A_valHL    OpcodeValue = 0x7e
	LD_A_A        OpcodeValue = 0x7f
	LD_vala16_SP  OpcodeValue = 0x08
	ADD_A_B       OpcodeValue = 0x80
	ADD_A_C       OpcodeValue = 0x81
	ADD_A_D       OpcodeValue = 0x82
	ADD_A_E       OpcodeValue = 0x83
	ADD_A_H       OpcodeValue = 0x84
	ADD_A_L       OpcodeValue = 0x85
	ADD_A_valHL   OpcodeValue = 0x86
	ADD_A_A       OpcodeValue = 0x87
	ADC_A_B       OpcodeValue = 0x88
	ADC_A_C       OpcodeValue = 0x89
	ADC_A_D       OpcodeValue = 0x8a
	ADC_A_E       OpcodeValue = 0x8b
	ADC_A_H       OpcodeValue = 0x8c
	ADC_A_L       OpcodeValue = 0x8d
	ADC_A_valHL   OpcodeValue = 0x8e
	ADC_A_A       OpcodeValue = 0x8f
	ADD_HL_BC     OpcodeValue = 0x09
	SUB_B         OpcodeValue = 0x90
	SUB_C         OpcodeValue = 0x91
	SUB_D         OpcodeValue = 0x92
	SUB_E         OpcodeValue = 0x93
	SUB_H         OpcodeValue = 0x94
	SUB_L         OpcodeValue = 0x95
	SUB_valHL     OpcodeValue = 0x96
	SUB_A         OpcodeValue = 0x97
	SBC_A_B       OpcodeValue = 0x98
	SBC_A_C       OpcodeValue = 0x99
	SBC_A_D       OpcodeValue = 0x9a
	SBC_A_E       OpcodeValue = 0x9b
	SBC_A_H       OpcodeValue = 0x9c
	SBC_A_L       OpcodeValue = 0x9d
	SBC_A_valHL   OpcodeValue = 0x9e
	SBC_A_A       OpcodeValue = 0x9f
	LD_A_valBC    OpcodeValue = 0x0a
	AND_B         OpcodeValue = 0xa0
	AND_C         OpcodeValue = 0xa1
	AND_D         OpcodeValue = 0xa2
	AND_E         OpcodeValue = 0xa3
	AND_H         OpcodeValue = 0xa4
	AND_L         OpcodeValue = 0xa5
	AND_valHL     OpcodeValue = 0xa6
	AND_A         OpcodeValue = 0xa7
	XOR_B         OpcodeValue = 0xa8
	XOR_C         OpcodeValue = 0xa9
	XOR_D         OpcodeValue = 0xaa
	XOR_E         OpcodeValue = 0xab
	XOR_H         OpcodeValue = 0xac
	XOR_L         OpcodeValue = 0xad
	XOR_valHL     OpcodeValue = 0xae
	XOR_A         OpcodeValue = 0xaf
	DEC_BC        OpcodeValue = 0x0b
	OR_B          OpcodeValue = 0xb0
	OR_C          OpcodeValue = 0xb1
	OR_D          OpcodeValue = 0xb2
	OR_E          OpcodeValue = 0xb3
	OR_H          OpcodeValue = 0xb4
	OR_L          OpcodeValue = 0xb5
	OR_valHL      OpcodeValue = 0xb6
	OR_A          OpcodeValue = 0xb7
	CP_B          OpcodeValue = 0xb8
	CP_C          OpcodeValue = 0xb9
	CP_D          OpcodeValue = 0xba
	CP_E          OpcodeValue = 0xbb
	CP_H          OpcodeValue = 0xbc
	CP_L          OpcodeValue = 0xbd
	CP_valHL      OpcodeValue = 0xbe
	CP_A          OpcodeValue = 0xbf
	INC_C         OpcodeValue = 0x0c
	RET_NZ        OpcodeValue = 0xc0
	POP_BC        OpcodeValue = 0xc1
	JP_NZ_a16     OpcodeValue = 0xc2
	JP_a16        OpcodeValue = 0xc3
	CALL_NZ_a16   OpcodeValue = 0xc4
	PUSH_BC       OpcodeValue = 0xc5
	ADD_A_d8      OpcodeValue = 0xc6
	RST_00H       OpcodeValue = 0xc7
	RET_Z         OpcodeValue = 0xc8
	RET           OpcodeValue = 0xc9
	JP_Z_a16      OpcodeValue = 0xca
	PREFIX_CB     OpcodeValue = 0xcb
	CALL_Z_a16    OpcodeValue = 0xcc
	CALL_a16      OpcodeValue = 0xcd
	ADC_A_d8      OpcodeValue = 0xce
	RST_08H       OpcodeValue = 0xcf
	DEC_C         OpcodeValue = 0x0d
	RET_NC        OpcodeValue = 0xd0
	POP_DE        OpcodeValue = 0xd1
	JP_NC_a16     OpcodeValue = 0xd2
	CALL_NC_a16   OpcodeValue = 0xd4
	PUSH_DE       OpcodeValue = 0xd5
	SUB_d8        OpcodeValue = 0xd6
	RST_10H       OpcodeValue = 0xd7
	RET_C         OpcodeValue = 0xd8
	RETI          OpcodeValue = 0xd9
	JP_C_a16      OpcodeValue = 0xda
	CALL_C_a16    OpcodeValue = 0xdc
	SBC_A_d8      OpcodeValue = 0xde
	RST_18H       OpcodeValue = 0xdf
	LD_C_d8       OpcodeValue = 0x0e
	LDH_vala8_A   OpcodeValue = 0xe0
	POP_HL        OpcodeValue = 0xe1
	LD_valC_A     OpcodeValue = 0xe2
	PUSH_HL       OpcodeValue = 0xe5
	AND_d8        OpcodeValue = 0xe6
	RST_20H       OpcodeValue = 0xe7
	ADD_SP_r8     OpcodeValue = 0xe8
	JP_valHL      OpcodeValue = 0xe9
	LD_vala16_A   OpcodeValue = 0xea
	XOR_d8        OpcodeValue = 0xee
	RST_28H       OpcodeValue = 0xef
	RRCA          OpcodeValue = 0x0f
	LDH_A_vala8   OpcodeValue = 0xf0
	POP_AF        OpcodeValue = 0xf1
	LD_A_valC     OpcodeValue = 0xf2
	DI            OpcodeValue = 0xf3
	PUSH_AF       OpcodeValue = 0xf5
	OR_d8         OpcodeValue = 0xf6
	RST_30H       OpcodeValue = 0xf7
	LD_HL_SPincr8 OpcodeValue = 0xf8
	LD_SP_HL      OpcodeValue = 0xf9
	LD_A_vala16   OpcodeValue = 0xfa
	EI            OpcodeValue = 0xfb
	CP_d8         OpcodeValue = 0xfe
	RST_38H       OpcodeValue = 0xff
)

const (
	RLC_B       OpcodeValue = 0x00
	RLC_C       OpcodeValue = 0x01
	RL_B        OpcodeValue = 0x10
	RL_C        OpcodeValue = 0x11
	RL_D        OpcodeValue = 0x12
	RL_E        OpcodeValue = 0x13
	RL_H        OpcodeValue = 0x14
	RL_L        OpcodeValue = 0x15
	RL_valHL    OpcodeValue = 0x16
	RL_A        OpcodeValue = 0x17
	RR_B        OpcodeValue = 0x18
	RR_C        OpcodeValue = 0x19
	RR_D        OpcodeValue = 0x1a
	RR_E        OpcodeValue = 0x1b
	RR_H        OpcodeValue = 0x1c
	RR_L        OpcodeValue = 0x1d
	RR_valHL    OpcodeValue = 0x1e
	RR_A        OpcodeValue = 0x1f
	RLC_D       OpcodeValue = 0x02
	SLA_B       OpcodeValue = 0x20
	SLA_C       OpcodeValue = 0x21
	SLA_D       OpcodeValue = 0x22
	SLA_E       OpcodeValue = 0x23
	SLA_H       OpcodeValue = 0x24
	SLA_L       OpcodeValue = 0x25
	SLA_valHL   OpcodeValue = 0x26
	SLA_A       OpcodeValue = 0x27
	SRA_B       OpcodeValue = 0x28
	SRA_C       OpcodeValue = 0x29
	SRA_D       OpcodeValue = 0x2a
	SRA_E       OpcodeValue = 0x2b
	SRA_H       OpcodeValue = 0x2c
	SRA_L       OpcodeValue = 0x2d
	SRA_valHL   OpcodeValue = 0x2e
	SRA_A       OpcodeValue = 0x2f
	RLC_E       OpcodeValue = 0x03
	SWAP_B      OpcodeValue = 0x30
	SWAP_C      OpcodeValue = 0x31
	SWAP_D      OpcodeValue = 0x32
	SWAP_E      OpcodeValue = 0x33
	SWAP_H      OpcodeValue = 0x34
	SWAP_L      OpcodeValue = 0x35
	SWAP_valHL  OpcodeValue = 0x36
	SWAP_A      OpcodeValue = 0x37
	SRL_B       OpcodeValue = 0x38
	SRL_C       OpcodeValue = 0x39
	SRL_D       OpcodeValue = 0x3a
	SRL_E       OpcodeValue = 0x3b
	SRL_H       OpcodeValue = 0x3c
	SRL_L       OpcodeValue = 0x3d
	SRL_valHL   OpcodeValue = 0x3e
	SRL_A       OpcodeValue = 0x3f
	RLC_H       OpcodeValue = 0x04
	BIT_0_B     OpcodeValue = 0x40
	BIT_0_C     OpcodeValue = 0x41
	BIT_0_D     OpcodeValue = 0x42
	BIT_0_E     OpcodeValue = 0x43
	BIT_0_H     OpcodeValue = 0x44
	BIT_0_L     OpcodeValue = 0x45
	BIT_0_valHL OpcodeValue = 0x46
	BIT_0_A     OpcodeValue = 0x47
	BIT_1_B     OpcodeValue = 0x48
	BIT_1_C     OpcodeValue = 0x49
	BIT_1_D     OpcodeValue = 0x4a
	BIT_1_E     OpcodeValue = 0x4b
	BIT_1_H     OpcodeValue = 0x4c
	BIT_1_L     OpcodeValue = 0x4d
	BIT_1_valHL OpcodeValue = 0x4e
	BIT_1_A     OpcodeValue = 0x4f
	RLC_L       OpcodeValue = 0x05
	BIT_2_B     OpcodeValue = 0x50
	BIT_2_C     OpcodeValue = 0x51
	BIT_2_D     OpcodeValue = 0x52
	BIT_2_E     OpcodeValue = 0x53
	BIT_2_H     OpcodeValue = 0x54
	BIT_2_L     OpcodeValue = 0x55
	BIT_2_valHL OpcodeValue = 0x56
	BIT_2_A     OpcodeValue = 0x57
	BIT_3_B     OpcodeValue = 0x58
	BIT_3_C     OpcodeValue = 0x59
	BIT_3_D     OpcodeValue = 0x5a
	BIT_3_E     OpcodeValue = 0x5b
	BIT_3_H     OpcodeValue = 0x5c
	BIT_3_L     OpcodeValue = 0x5d
	BIT_3_valHL OpcodeValue = 0x5e
	BIT_3_A     OpcodeValue = 0x5f
	RLC_valHL   OpcodeValue = 0x06
	BIT_4_B     OpcodeValue = 0x60
	BIT_4_C     OpcodeValue = 0x61
	BIT_4_D     OpcodeValue = 0x62
	BIT_4_E     OpcodeValue = 0x63
	BIT_4_H     OpcodeValue = 0x64
	BIT_4_L     OpcodeValue = 0x65
	BIT_4_valHL OpcodeValue = 0x66
	BIT_4_A     OpcodeValue = 0x67
	BIT_5_B     OpcodeValue = 0x68
	BIT_5_C     OpcodeValue = 0x69
	BIT_5_D     OpcodeValue = 0x6a
	BIT_5_E     OpcodeValue = 0x6b
	BIT_5_H     OpcodeValue = 0x6c
	BIT_5_L     OpcodeValue = 0x6d
	BIT_5_valHL OpcodeValue = 0x6e
	BIT_5_A     OpcodeValue = 0x6f
	RLC_A       OpcodeValue = 0x07
	BIT_6_B     OpcodeValue = 0x70
	BIT_6_C     OpcodeValue = 0x71
	BIT_6_D     OpcodeValue = 0x72
	BIT_6_E     OpcodeValue = 0x73
	BIT_6_H     OpcodeValue = 0x74
	BIT_6_L     OpcodeValue = 0x75
	BIT_6_valHL OpcodeValue = 0x76
	BIT_6_A     OpcodeValue = 0x77
	BIT_7_B     OpcodeValue = 0x78
	BIT_7_C     OpcodeValue = 0x79
	BIT_7_D     OpcodeValue = 0x7a
	BIT_7_E     OpcodeValue = 0x7b
	BIT_7_H     OpcodeValue = 0x7c
	BIT_7_L     OpcodeValue = 0x7d
	BIT_7_valHL OpcodeValue = 0x7e
	BIT_7_A     OpcodeValue = 0x7f
	RRC_B       OpcodeValue = 0x08
	RES_0_B     OpcodeValue = 0x80
	RES_0_C     OpcodeValue = 0x81
	RES_0_D     OpcodeValue = 0x82
	RES_0_E     OpcodeValue = 0x83
	RES_0_H     OpcodeValue = 0x84
	RES_0_L     OpcodeValue = 0x85
	RES_0_valHL OpcodeValue = 0x86
	RES_0_A     OpcodeValue = 0x87
	RES_1_B     OpcodeValue = 0x88
	RES_1_C     OpcodeValue = 0x89
	RES_1_D     OpcodeValue = 0x8a
	RES_1_E     OpcodeValue = 0x8b
	RES_1_H     OpcodeValue = 0x8c
	RES_1_L     OpcodeValue = 0x8d
	RES_1_valHL OpcodeValue = 0x8e
	RES_1_A     OpcodeValue = 0x8f
	RRC_C       OpcodeValue = 0x09
	RES_2_B     OpcodeValue = 0x90
	RES_2_C     OpcodeValue = 0x91
	RES_2_D     OpcodeValue = 0x92
	RES_2_E     OpcodeValue = 0x93
	RES_2_H     OpcodeValue = 0x94
	RES_2_L     OpcodeValue = 0x95
	RES_2_valHL OpcodeValue = 0x96
	RES_2_A     OpcodeValue = 0x97
	RES_3_B     OpcodeValue = 0x98
	RES_3_C     OpcodeValue = 0x99
	RES_3_D     OpcodeValue = 0x9a
	RES_3_E     OpcodeValue = 0x9b
	RES_3_H     OpcodeValue = 0x9c
	RES_3_L     OpcodeValue = 0x9d
	RES_3_valHL OpcodeValue = 0x9e
	RES_3_A     OpcodeValue = 0x9f
	RRC_D       OpcodeValue = 0x0a
	RES_4_B     OpcodeValue = 0xa0
	RES_4_C     OpcodeValue = 0xa1
	RES_4_D     OpcodeValue = 0xa2
	RES_4_E     OpcodeValue = 0xa3
	RES_4_H     OpcodeValue = 0xa4
	RES_4_L     OpcodeValue = 0xa5
	RES_4_valHL OpcodeValue = 0xa6
	RES_4_A     OpcodeValue = 0xa7
	RES_5_B     OpcodeValue = 0xa8
	RES_5_C     OpcodeValue = 0xa9
	RES_5_D     OpcodeValue = 0xaa
	RES_5_E     OpcodeValue = 0xab
	RES_5_H     OpcodeValue = 0xac
	RES_5_L     OpcodeValue = 0xad
	RES_5_valHL OpcodeValue = 0xae
	RES_5_A     OpcodeValue = 0xaf
	RRC_E       OpcodeValue = 0x0b
	RES_6_B     OpcodeValue = 0xb0
	RES_6_C     OpcodeValue = 0xb1
	RES_6_D     OpcodeValue = 0xb2
	RES_6_E     OpcodeValue = 0xb3
	RES_6_H     OpcodeValue = 0xb4
	RES_6_L     OpcodeValue = 0xb5
	RES_6_valHL OpcodeValue = 0xb6
	RES_6_A     OpcodeValue = 0xb7
	RES_7_B     OpcodeValue = 0xb8
	RES_7_C     OpcodeValue = 0xb9
	RES_7_D     OpcodeValue = 0xba
	RES_7_E     OpcodeValue = 0xbb
	RES_7_H     OpcodeValue = 0xbc
	RES_7_L     OpcodeValue = 0xbd
	RES_7_valHL OpcodeValue = 0xbe
	RES_7_A     OpcodeValue = 0xbf
	RRC_H       OpcodeValue = 0x0c
	SET_0_B     OpcodeValue = 0xc0
	SET_0_C     OpcodeValue = 0xc1
	SET_0_D     OpcodeValue = 0xc2
	SET_0_E     OpcodeValue = 0xc3
	SET_0_H     OpcodeValue = 0xc4
	SET_0_L     OpcodeValue = 0xc5
	SET_0_valHL OpcodeValue = 0xc6
	SET_0_A     OpcodeValue = 0xc7
	SET_1_B     OpcodeValue = 0xc8
	SET_1_C     OpcodeValue = 0xc9
	SET_1_D     OpcodeValue = 0xca
	SET_1_E     OpcodeValue = 0xcb
	SET_1_H     OpcodeValue = 0xcc
	SET_1_L     OpcodeValue = 0xcd
	SET_1_valHL OpcodeValue = 0xce
	SET_1_A     OpcodeValue = 0xcf
	RRC_L       OpcodeValue = 0x0d
	SET_2_B     OpcodeValue = 0xd0
	SET_2_C     OpcodeValue = 0xd1
	SET_2_D     OpcodeValue = 0xd2
	SET_2_E     OpcodeValue = 0xd3
	SET_2_H     OpcodeValue = 0xd4
	SET_2_L     OpcodeValue = 0xd5
	SET_2_valHL OpcodeValue = 0xd6
	SET_2_A     OpcodeValue = 0xd7
	SET_3_B     OpcodeValue = 0xd8
	SET_3_C     OpcodeValue = 0xd9
	SET_3_D     OpcodeValue = 0xda
	SET_3_E     OpcodeValue = 0xdb
	SET_3_H     OpcodeValue = 0xdc
	SET_3_L     OpcodeValue = 0xdd
	SET_3_valHL OpcodeValue = 0xde
	SET_3_A     OpcodeValue = 0xdf
	RRC_valHL   OpcodeValue = 0x0e
	SET_4_B     OpcodeValue = 0xe0
	SET_4_C     OpcodeValue = 0xe1
	SET_4_D     OpcodeValue = 0xe2
	SET_4_E     OpcodeValue = 0xe3
	SET_4_H     OpcodeValue = 0xe4
	SET_4_L     OpcodeValue = 0xe5
	SET_4_valHL OpcodeValue = 0xe6
	SET_4_A     OpcodeValue = 0xe7
	SET_5_B     OpcodeValue = 0xe8
	SET_5_C     OpcodeValue = 0xe9
	SET_5_D     OpcodeValue = 0xea
	SET_5_E     OpcodeValue = 0xeb
	SET_5_H     OpcodeValue = 0xec
	SET_5_L     OpcodeValue = 0xed
	SET_5_valHL OpcodeValue = 0xee
	SET_5_A     OpcodeValue = 0xef
	RRC_A       OpcodeValue = 0x0f
	SET_6_B     OpcodeValue = 0xf0
	SET_6_C     OpcodeValue = 0xf1
	SET_6_D     OpcodeValue = 0xf2
	SET_6_E     OpcodeValue = 0xf3
	SET_6_H     OpcodeValue = 0xf4
	SET_6_L     OpcodeValue = 0xf5
	SET_6_valHL OpcodeValue = 0xf6
	SET_6_A     OpcodeValue = 0xf7
	SET_7_B     OpcodeValue = 0xf8
	SET_7_C     OpcodeValue = 0xf9
	SET_7_D     OpcodeValue = 0xfa
	SET_7_E     OpcodeValue = 0xfb
	SET_7_H     OpcodeValue = 0xfc
	SET_7_L     OpcodeValue = 0xfd
	SET_7_valHL OpcodeValue = 0xfe
	SET_7_A     OpcodeValue = 0xff
)

var unprefixedOpcodes = map[OpcodeValue]Opcode{
	0x00: Opcode{0x00, false, "NOP", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x01: Opcode{0x01, false, "LD BC, d16", 3, 12, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x10: Opcode{0x10, false, "STOP 0", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x11: Opcode{0x11, false, "LD DE, d16", 3, 12, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x12: Opcode{0x12, false, "LD (DE), A", 1, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x13: Opcode{0x13, false, "INC DE", 1, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x14: Opcode{0x14, false, "INC D", 1, 4, 0, Flags{CanChange, IsReset, CanChange, NoChange}},
	0x15: Opcode{0x15, false, "DEC D", 1, 4, 0, Flags{CanChange, IsSet, CanChange, NoChange}},
	0x16: Opcode{0x16, false, "LD D, d8", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x17: Opcode{0x17, false, "RLA", 1, 4, 0, Flags{IsReset, IsReset, IsReset, CanChange}},
	0x18: Opcode{0x18, false, "JR r8", 2, 12, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x19: Opcode{0x19, false, "ADD HL, DE", 1, 8, 0, Flags{NoChange, IsReset, CanChange, CanChange}},
	0x1a: Opcode{0x1a, false, "LD A, (DE)", 1, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x1b: Opcode{0x1b, false, "DEC DE", 1, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x1c: Opcode{0x1c, false, "INC E", 1, 4, 0, Flags{CanChange, IsReset, CanChange, NoChange}},
	0x1d: Opcode{0x1d, false, "DEC E", 1, 4, 0, Flags{CanChange, IsSet, CanChange, NoChange}},
	0x1e: Opcode{0x1e, false, "LD E, d8", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x1f: Opcode{0x1f, false, "RRA", 1, 4, 0, Flags{IsReset, IsReset, IsReset, CanChange}},
	0x02: Opcode{0x02, false, "LD (BC), A", 1, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x20: Opcode{0x20, false, "JR NZ, r8", 2, 12, 8, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x21: Opcode{0x21, false, "LD HL, d16", 3, 12, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x22: Opcode{0x22, false, "LD (HL+), A", 1, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x23: Opcode{0x23, false, "INC HL", 1, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x24: Opcode{0x24, false, "INC H", 1, 4, 0, Flags{CanChange, IsReset, CanChange, NoChange}},
	0x25: Opcode{0x25, false, "DEC H", 1, 4, 0, Flags{CanChange, IsSet, CanChange, NoChange}},
	0x26: Opcode{0x26, false, "LD H, d8", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x27: Opcode{0x27, false, "DAA", 1, 4, 0, Flags{CanChange, NoChange, IsReset, CanChange}},
	0x28: Opcode{0x28, false, "JR Z, r8", 2, 12, 8, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x29: Opcode{0x29, false, "ADD HL, HL", 1, 8, 0, Flags{NoChange, IsReset, CanChange, CanChange}},
	0x2a: Opcode{0x2a, false, "LD A, (HL+)", 1, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x2b: Opcode{0x2b, false, "DEC HL", 1, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x2c: Opcode{0x2c, false, "INC L", 1, 4, 0, Flags{CanChange, IsReset, CanChange, NoChange}},
	0x2d: Opcode{0x2d, false, "DEC L", 1, 4, 0, Flags{CanChange, IsSet, CanChange, NoChange}},
	0x2e: Opcode{0x2e, false, "LD L, d8", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x2f: Opcode{0x2f, false, "CPL", 1, 4, 0, Flags{NoChange, IsSet, IsSet, NoChange}},
	0x03: Opcode{0x03, false, "INC BC", 1, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x30: Opcode{0x30, false, "JR NC, r8", 2, 12, 8, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x31: Opcode{0x31, false, "LD SP, d16", 3, 12, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x32: Opcode{0x32, false, "LD (HL-), A", 1, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x33: Opcode{0x33, false, "INC SP", 1, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x34: Opcode{0x34, false, "INC (HL)", 1, 12, 0, Flags{CanChange, IsReset, CanChange, NoChange}},
	0x35: Opcode{0x35, false, "DEC (HL)", 1, 12, 0, Flags{CanChange, IsSet, CanChange, NoChange}},
	0x36: Opcode{0x36, false, "LD (HL), d8", 2, 12, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x37: Opcode{0x37, false, "SCF", 1, 4, 0, Flags{NoChange, IsReset, IsReset, IsSet}},
	0x38: Opcode{0x38, false, "JR C, r8", 2, 12, 8, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x39: Opcode{0x39, false, "ADD HL, SP", 1, 8, 0, Flags{NoChange, IsReset, CanChange, CanChange}},
	0x3a: Opcode{0x3a, false, "LD A, (HL-)", 1, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x3b: Opcode{0x3b, false, "DEC SP", 1, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x3c: Opcode{0x3c, false, "INC A", 1, 4, 0, Flags{CanChange, IsReset, CanChange, NoChange}},
	0x3d: Opcode{0x3d, false, "DEC A", 1, 4, 0, Flags{CanChange, IsSet, CanChange, NoChange}},
	0x3e: Opcode{0x3e, false, "LD A, d8", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x3f: Opcode{0x3f, false, "CCF", 1, 4, 0, Flags{NoChange, IsReset, IsReset, CanChange}},
	0x04: Opcode{0x04, false, "INC B", 1, 4, 0, Flags{CanChange, IsReset, CanChange, NoChange}},
	0x40: Opcode{0x40, false, "LD B, B", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x41: Opcode{0x41, false, "LD B, C", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x42: Opcode{0x42, false, "LD B, D", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x43: Opcode{0x43, false, "LD B, E", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x44: Opcode{0x44, false, "LD B, H", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x45: Opcode{0x45, false, "LD B, L", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x46: Opcode{0x46, false, "LD B, (HL)", 1, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x47: Opcode{0x47, false, "LD B, A", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x48: Opcode{0x48, false, "LD C, B", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x49: Opcode{0x49, false, "LD C, C", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x4a: Opcode{0x4a, false, "LD C, D", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x4b: Opcode{0x4b, false, "LD C, E", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x4c: Opcode{0x4c, false, "LD C, H", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x4d: Opcode{0x4d, false, "LD C, L", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x4e: Opcode{0x4e, false, "LD C, (HL)", 1, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x4f: Opcode{0x4f, false, "LD C, A", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x05: Opcode{0x05, false, "DEC B", 1, 4, 0, Flags{CanChange, IsSet, CanChange, NoChange}},
	0x50: Opcode{0x50, false, "LD D, B", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x51: Opcode{0x51, false, "LD D, C", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x52: Opcode{0x52, false, "LD D, D", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x53: Opcode{0x53, false, "LD D, E", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x54: Opcode{0x54, false, "LD D, H", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x55: Opcode{0x55, false, "LD D, L", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x56: Opcode{0x56, false, "LD D, (HL)", 1, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x57: Opcode{0x57, false, "LD D, A", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x58: Opcode{0x58, false, "LD E, B", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x59: Opcode{0x59, false, "LD E, C", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x5a: Opcode{0x5a, false, "LD E, D", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x5b: Opcode{0x5b, false, "LD E, E", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x5c: Opcode{0x5c, false, "LD E, H", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x5d: Opcode{0x5d, false, "LD E, L", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x5e: Opcode{0x5e, false, "LD E, (HL)", 1, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x5f: Opcode{0x5f, false, "LD E, A", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x06: Opcode{0x06, false, "LD B, d8", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x60: Opcode{0x60, false, "LD H, B", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x61: Opcode{0x61, false, "LD H, C", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x62: Opcode{0x62, false, "LD H, D", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x63: Opcode{0x63, false, "LD H, E", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x64: Opcode{0x64, false, "LD H, H", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x65: Opcode{0x65, false, "LD H, L", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x66: Opcode{0x66, false, "LD H, (HL)", 1, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x67: Opcode{0x67, false, "LD H, A", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x68: Opcode{0x68, false, "LD L, B", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x69: Opcode{0x69, false, "LD L, C", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x6a: Opcode{0x6a, false, "LD L, D", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x6b: Opcode{0x6b, false, "LD L, E", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x6c: Opcode{0x6c, false, "LD L, H", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x6d: Opcode{0x6d, false, "LD L, L", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x6e: Opcode{0x6e, false, "LD L, (HL)", 1, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x6f: Opcode{0x6f, false, "LD L, A", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x07: Opcode{0x07, false, "RLCA", 1, 4, 0, Flags{IsReset, IsReset, IsReset, CanChange}},
	0x70: Opcode{0x70, false, "LD (HL), B", 1, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x71: Opcode{0x71, false, "LD (HL), C", 1, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x72: Opcode{0x72, false, "LD (HL), D", 1, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x73: Opcode{0x73, false, "LD (HL), E", 1, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x74: Opcode{0x74, false, "LD (HL), H", 1, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x75: Opcode{0x75, false, "LD (HL), L", 1, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x76: Opcode{0x76, false, "HALT", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x77: Opcode{0x77, false, "LD (HL), A", 1, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x78: Opcode{0x78, false, "LD A, B", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x79: Opcode{0x79, false, "LD A, C", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x7a: Opcode{0x7a, false, "LD A, D", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x7b: Opcode{0x7b, false, "LD A, E", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x7c: Opcode{0x7c, false, "LD A, H", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x7d: Opcode{0x7d, false, "LD A, L", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x7e: Opcode{0x7e, false, "LD A, (HL)", 1, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x7f: Opcode{0x7f, false, "LD A, A", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x08: Opcode{0x08, false, "LD (a16), SP", 3, 20, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x80: Opcode{0x80, false, "ADD A, B", 1, 4, 0, Flags{CanChange, IsReset, CanChange, CanChange}},
	0x81: Opcode{0x81, false, "ADD A, C", 1, 4, 0, Flags{CanChange, IsReset, CanChange, CanChange}},
	0x82: Opcode{0x82, false, "ADD A, D", 1, 4, 0, Flags{CanChange, IsReset, CanChange, CanChange}},
	0x83: Opcode{0x83, false, "ADD A, E", 1, 4, 0, Flags{CanChange, IsReset, CanChange, CanChange}},
	0x84: Opcode{0x84, false, "ADD A, H", 1, 4, 0, Flags{CanChange, IsReset, CanChange, CanChange}},
	0x85: Opcode{0x85, false, "ADD A, L", 1, 4, 0, Flags{CanChange, IsReset, CanChange, CanChange}},
	0x86: Opcode{0x86, false, "ADD A, (HL)", 1, 8, 0, Flags{CanChange, IsReset, CanChange, CanChange}},
	0x87: Opcode{0x87, false, "ADD A, A", 1, 4, 0, Flags{CanChange, IsReset, CanChange, CanChange}},
	0x88: Opcode{0x88, false, "ADC A, B", 1, 4, 0, Flags{CanChange, IsReset, CanChange, CanChange}},
	0x89: Opcode{0x89, false, "ADC A, C", 1, 4, 0, Flags{CanChange, IsReset, CanChange, CanChange}},
	0x8a: Opcode{0x8a, false, "ADC A, D", 1, 4, 0, Flags{CanChange, IsReset, CanChange, CanChange}},
	0x8b: Opcode{0x8b, false, "ADC A, E", 1, 4, 0, Flags{CanChange, IsReset, CanChange, CanChange}},
	0x8c: Opcode{0x8c, false, "ADC A, H", 1, 4, 0, Flags{CanChange, IsReset, CanChange, CanChange}},
	0x8d: Opcode{0x8d, false, "ADC A, L", 1, 4, 0, Flags{CanChange, IsReset, CanChange, CanChange}},
	0x8e: Opcode{0x8e, false, "ADC A, (HL)", 1, 8, 0, Flags{CanChange, IsReset, CanChange, CanChange}},
	0x8f: Opcode{0x8f, false, "ADC A, A", 1, 4, 0, Flags{CanChange, IsReset, CanChange, CanChange}},
	0x09: Opcode{0x09, false, "ADD HL, BC", 1, 8, 0, Flags{NoChange, IsReset, CanChange, CanChange}},
	0x90: Opcode{0x90, false, "SUB B", 1, 4, 0, Flags{CanChange, IsSet, CanChange, CanChange}},
	0x91: Opcode{0x91, false, "SUB C", 1, 4, 0, Flags{CanChange, IsSet, CanChange, CanChange}},
	0x92: Opcode{0x92, false, "SUB D", 1, 4, 0, Flags{CanChange, IsSet, CanChange, CanChange}},
	0x93: Opcode{0x93, false, "SUB E", 1, 4, 0, Flags{CanChange, IsSet, CanChange, CanChange}},
	0x94: Opcode{0x94, false, "SUB H", 1, 4, 0, Flags{CanChange, IsSet, CanChange, CanChange}},
	0x95: Opcode{0x95, false, "SUB L", 1, 4, 0, Flags{CanChange, IsSet, CanChange, CanChange}},
	0x96: Opcode{0x96, false, "SUB (HL)", 1, 8, 0, Flags{CanChange, IsSet, CanChange, CanChange}},
	0x97: Opcode{0x97, false, "SUB A", 1, 4, 0, Flags{CanChange, IsSet, CanChange, CanChange}},
	0x98: Opcode{0x98, false, "SBC A, B", 1, 4, 0, Flags{CanChange, IsSet, CanChange, CanChange}},
	0x99: Opcode{0x99, false, "SBC A, C", 1, 4, 0, Flags{CanChange, IsSet, CanChange, CanChange}},
	0x9a: Opcode{0x9a, false, "SBC A, D", 1, 4, 0, Flags{CanChange, IsSet, CanChange, CanChange}},
	0x9b: Opcode{0x9b, false, "SBC A, E", 1, 4, 0, Flags{CanChange, IsSet, CanChange, CanChange}},
	0x9c: Opcode{0x9c, false, "SBC A, H", 1, 4, 0, Flags{CanChange, IsSet, CanChange, CanChange}},
	0x9d: Opcode{0x9d, false, "SBC A, L", 1, 4, 0, Flags{CanChange, IsSet, CanChange, CanChange}},
	0x9e: Opcode{0x9e, false, "SBC A, (HL)", 1, 8, 0, Flags{CanChange, IsSet, CanChange, CanChange}},
	0x9f: Opcode{0x9f, false, "SBC A, A", 1, 4, 0, Flags{CanChange, IsSet, CanChange, CanChange}},
	0x0a: Opcode{0x0a, false, "LD A, (BC)", 1, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xa0: Opcode{0xa0, false, "AND B", 1, 4, 0, Flags{CanChange, IsReset, IsSet, IsReset}},
	0xa1: Opcode{0xa1, false, "AND C", 1, 4, 0, Flags{CanChange, IsReset, IsSet, IsReset}},
	0xa2: Opcode{0xa2, false, "AND D", 1, 4, 0, Flags{CanChange, IsReset, IsSet, IsReset}},
	0xa3: Opcode{0xa3, false, "AND E", 1, 4, 0, Flags{CanChange, IsReset, IsSet, IsReset}},
	0xa4: Opcode{0xa4, false, "AND H", 1, 4, 0, Flags{CanChange, IsReset, IsSet, IsReset}},
	0xa5: Opcode{0xa5, false, "AND L", 1, 4, 0, Flags{CanChange, IsReset, IsSet, IsReset}},
	0xa6: Opcode{0xa6, false, "AND (HL)", 1, 8, 0, Flags{CanChange, IsReset, IsSet, IsReset}},
	0xa7: Opcode{0xa7, false, "AND A", 1, 4, 0, Flags{CanChange, IsReset, IsSet, IsReset}},
	0xa8: Opcode{0xa8, false, "XOR B", 1, 4, 0, Flags{CanChange, IsReset, IsReset, IsReset}},
	0xa9: Opcode{0xa9, false, "XOR C", 1, 4, 0, Flags{CanChange, IsReset, IsReset, IsReset}},
	0xaa: Opcode{0xaa, false, "XOR D", 1, 4, 0, Flags{CanChange, IsReset, IsReset, IsReset}},
	0xab: Opcode{0xab, false, "XOR E", 1, 4, 0, Flags{CanChange, IsReset, IsReset, IsReset}},
	0xac: Opcode{0xac, false, "XOR H", 1, 4, 0, Flags{CanChange, IsReset, IsReset, IsReset}},
	0xad: Opcode{0xad, false, "XOR L", 1, 4, 0, Flags{CanChange, IsReset, IsReset, IsReset}},
	0xae: Opcode{0xae, false, "XOR (HL)", 1, 8, 0, Flags{CanChange, IsReset, IsReset, IsReset}},
	0xaf: Opcode{0xaf, false, "XOR A", 1, 4, 0, Flags{CanChange, IsReset, IsReset, IsReset}},
	0x0b: Opcode{0x0b, false, "DEC BC", 1, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xb0: Opcode{0xb0, false, "OR B", 1, 4, 0, Flags{CanChange, IsReset, IsReset, IsReset}},
	0xb1: Opcode{0xb1, false, "OR C", 1, 4, 0, Flags{CanChange, IsReset, IsReset, IsReset}},
	0xb2: Opcode{0xb2, false, "OR D", 1, 4, 0, Flags{CanChange, IsReset, IsReset, IsReset}},
	0xb3: Opcode{0xb3, false, "OR E", 1, 4, 0, Flags{CanChange, IsReset, IsReset, IsReset}},
	0xb4: Opcode{0xb4, false, "OR H", 1, 4, 0, Flags{CanChange, IsReset, IsReset, IsReset}},
	0xb5: Opcode{0xb5, false, "OR L", 1, 4, 0, Flags{CanChange, IsReset, IsReset, IsReset}},
	0xb6: Opcode{0xb6, false, "OR (HL)", 1, 8, 0, Flags{CanChange, IsReset, IsReset, IsReset}},
	0xb7: Opcode{0xb7, false, "OR A", 1, 4, 0, Flags{CanChange, IsReset, IsReset, IsReset}},
	0xb8: Opcode{0xb8, false, "CP B", 1, 4, 0, Flags{CanChange, IsSet, CanChange, CanChange}},
	0xb9: Opcode{0xb9, false, "CP C", 1, 4, 0, Flags{CanChange, IsSet, CanChange, CanChange}},
	0xba: Opcode{0xba, false, "CP D", 1, 4, 0, Flags{CanChange, IsSet, CanChange, CanChange}},
	0xbb: Opcode{0xbb, false, "CP E", 1, 4, 0, Flags{CanChange, IsSet, CanChange, CanChange}},
	0xbc: Opcode{0xbc, false, "CP H", 1, 4, 0, Flags{CanChange, IsSet, CanChange, CanChange}},
	0xbd: Opcode{0xbd, false, "CP L", 1, 4, 0, Flags{CanChange, IsSet, CanChange, CanChange}},
	0xbe: Opcode{0xbe, false, "CP (HL)", 1, 8, 0, Flags{CanChange, IsSet, CanChange, CanChange}},
	0xbf: Opcode{0xbf, false, "CP A", 1, 4, 0, Flags{CanChange, IsSet, CanChange, CanChange}},
	0x0c: Opcode{0x0c, false, "INC C", 1, 4, 0, Flags{CanChange, IsReset, CanChange, NoChange}},
	0xc0: Opcode{0xc0, false, "RET NZ", 1, 20, 8, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xc1: Opcode{0xc1, false, "POP BC", 1, 12, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xc2: Opcode{0xc2, false, "JP NZ, a16", 3, 16, 12, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xc3: Opcode{0xc3, false, "JP a16", 3, 16, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xc4: Opcode{0xc4, false, "CALL NZ, a16", 3, 24, 12, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xc5: Opcode{0xc5, false, "PUSH BC", 1, 16, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xc6: Opcode{0xc6, false, "ADD A, d8", 2, 8, 0, Flags{CanChange, IsReset, CanChange, CanChange}},
	0xc7: Opcode{0xc7, false, "RST 00H", 1, 16, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xc8: Opcode{0xc8, false, "RET Z", 1, 20, 8, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xc9: Opcode{0xc9, false, "RET", 1, 16, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xca: Opcode{0xca, false, "JP Z, a16", 3, 16, 12, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xcb: Opcode{0xcb, false, "PREFIX CB", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xcc: Opcode{0xcc, false, "CALL Z, a16", 3, 24, 12, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xcd: Opcode{0xcd, false, "CALL a16", 3, 24, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xce: Opcode{0xce, false, "ADC A, d8", 2, 8, 0, Flags{CanChange, IsReset, CanChange, CanChange}},
	0xcf: Opcode{0xcf, false, "RST 08H", 1, 16, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x0d: Opcode{0x0d, false, "DEC C", 1, 4, 0, Flags{CanChange, IsSet, CanChange, NoChange}},
	0xd0: Opcode{0xd0, false, "RET NC", 1, 20, 8, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xd1: Opcode{0xd1, false, "POP DE", 1, 12, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xd2: Opcode{0xd2, false, "JP NC, a16", 3, 16, 12, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xd4: Opcode{0xd4, false, "CALL NC, a16", 3, 24, 12, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xd5: Opcode{0xd5, false, "PUSH DE", 1, 16, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xd6: Opcode{0xd6, false, "SUB d8", 2, 8, 0, Flags{CanChange, IsSet, CanChange, CanChange}},
	0xd7: Opcode{0xd7, false, "RST 10H", 1, 16, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xd8: Opcode{0xd8, false, "RET C", 1, 20, 8, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xd9: Opcode{0xd9, false, "RETI", 1, 16, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xda: Opcode{0xda, false, "JP C, a16", 3, 16, 12, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xdc: Opcode{0xdc, false, "CALL C, a16", 3, 24, 12, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xde: Opcode{0xde, false, "SBC A, d8", 2, 8, 0, Flags{CanChange, IsSet, CanChange, CanChange}},
	0xdf: Opcode{0xdf, false, "RST 18H", 1, 16, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x0e: Opcode{0x0e, false, "LD C, d8", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xe0: Opcode{0xe0, false, "LDH (a8), A", 2, 12, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xe1: Opcode{0xe1, false, "POP HL", 1, 12, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xe2: Opcode{0xe2, false, "LD (C), A", 1, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xe5: Opcode{0xe5, false, "PUSH HL", 1, 16, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xe6: Opcode{0xe6, false, "AND d8", 2, 8, 0, Flags{CanChange, IsReset, IsSet, IsReset}},
	0xe7: Opcode{0xe7, false, "RST 20H", 1, 16, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xe8: Opcode{0xe8, false, "ADD SP, r8", 2, 16, 0, Flags{IsReset, IsReset, CanChange, CanChange}},
	0xe9: Opcode{0xe9, false, "JP (HL)", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xea: Opcode{0xea, false, "LD (a16), A", 3, 16, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xee: Opcode{0xee, false, "XOR d8", 2, 8, 0, Flags{CanChange, IsReset, IsReset, IsReset}},
	0xef: Opcode{0xef, false, "RST 28H", 1, 16, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x0f: Opcode{0x0f, false, "RRCA", 1, 4, 0, Flags{IsReset, IsReset, IsReset, CanChange}},
	0xf0: Opcode{0xf0, false, "LDH A, (a8)", 2, 12, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xf1: Opcode{0xf1, false, "POP AF", 1, 12, 0, Flags{CanChange, CanChange, CanChange, CanChange}},
	0xf2: Opcode{0xf2, false, "LD A, (C)", 1, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xf3: Opcode{0xf3, false, "DI", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xf5: Opcode{0xf5, false, "PUSH AF", 1, 16, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xf6: Opcode{0xf6, false, "OR d8", 2, 8, 0, Flags{CanChange, IsReset, IsReset, IsReset}},
	0xf7: Opcode{0xf7, false, "RST 30H", 1, 16, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xf8: Opcode{0xf8, false, "LD HL, SP+r8", 2, 12, 0, Flags{IsReset, IsReset, CanChange, CanChange}},
	0xf9: Opcode{0xf9, false, "LD SP, HL", 1, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xfa: Opcode{0xfa, false, "LD A, (a16)", 3, 16, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xfb: Opcode{0xfb, false, "EI", 1, 4, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xfe: Opcode{0xfe, false, "CP d8", 2, 8, 0, Flags{CanChange, IsSet, CanChange, CanChange}},
	0xff: Opcode{0xff, false, "RST 38H", 1, 16, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
}

var prefixedOpcodes = map[OpcodeValue]Opcode{
	0x00: Opcode{0x00, true, "RLC B", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x01: Opcode{0x01, true, "RLC C", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x10: Opcode{0x10, true, "RL B", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x11: Opcode{0x11, true, "RL C", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x12: Opcode{0x12, true, "RL D", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x13: Opcode{0x13, true, "RL E", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x14: Opcode{0x14, true, "RL H", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x15: Opcode{0x15, true, "RL L", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x16: Opcode{0x16, true, "RL (HL)", 2, 16, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x17: Opcode{0x17, true, "RL A", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x18: Opcode{0x18, true, "RR B", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x19: Opcode{0x19, true, "RR C", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x1a: Opcode{0x1a, true, "RR D", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x1b: Opcode{0x1b, true, "RR E", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x1c: Opcode{0x1c, true, "RR H", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x1d: Opcode{0x1d, true, "RR L", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x1e: Opcode{0x1e, true, "RR (HL)", 2, 16, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x1f: Opcode{0x1f, true, "RR A", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x02: Opcode{0x02, true, "RLC D", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x20: Opcode{0x20, true, "SLA B", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x21: Opcode{0x21, true, "SLA C", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x22: Opcode{0x22, true, "SLA D", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x23: Opcode{0x23, true, "SLA E", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x24: Opcode{0x24, true, "SLA H", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x25: Opcode{0x25, true, "SLA L", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x26: Opcode{0x26, true, "SLA (HL)", 2, 16, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x27: Opcode{0x27, true, "SLA A", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x28: Opcode{0x28, true, "SRA B", 2, 8, 0, Flags{CanChange, IsReset, IsReset, IsReset}},
	0x29: Opcode{0x29, true, "SRA C", 2, 8, 0, Flags{CanChange, IsReset, IsReset, IsReset}},
	0x2a: Opcode{0x2a, true, "SRA D", 2, 8, 0, Flags{CanChange, IsReset, IsReset, IsReset}},
	0x2b: Opcode{0x2b, true, "SRA E", 2, 8, 0, Flags{CanChange, IsReset, IsReset, IsReset}},
	0x2c: Opcode{0x2c, true, "SRA H", 2, 8, 0, Flags{CanChange, IsReset, IsReset, IsReset}},
	0x2d: Opcode{0x2d, true, "SRA L", 2, 8, 0, Flags{CanChange, IsReset, IsReset, IsReset}},
	0x2e: Opcode{0x2e, true, "SRA (HL)", 2, 16, 0, Flags{CanChange, IsReset, IsReset, IsReset}},
	0x2f: Opcode{0x2f, true, "SRA A", 2, 8, 0, Flags{CanChange, IsReset, IsReset, IsReset}},
	0x03: Opcode{0x03, true, "RLC E", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x30: Opcode{0x30, true, "SWAP B", 2, 8, 0, Flags{CanChange, IsReset, IsReset, IsReset}},
	0x31: Opcode{0x31, true, "SWAP C", 2, 8, 0, Flags{CanChange, IsReset, IsReset, IsReset}},
	0x32: Opcode{0x32, true, "SWAP D", 2, 8, 0, Flags{CanChange, IsReset, IsReset, IsReset}},
	0x33: Opcode{0x33, true, "SWAP E", 2, 8, 0, Flags{CanChange, IsReset, IsReset, IsReset}},
	0x34: Opcode{0x34, true, "SWAP H", 2, 8, 0, Flags{CanChange, IsReset, IsReset, IsReset}},
	0x35: Opcode{0x35, true, "SWAP L", 2, 8, 0, Flags{CanChange, IsReset, IsReset, IsReset}},
	0x36: Opcode{0x36, true, "SWAP (HL)", 2, 16, 0, Flags{CanChange, IsReset, IsReset, IsReset}},
	0x37: Opcode{0x37, true, "SWAP A", 2, 8, 0, Flags{CanChange, IsReset, IsReset, IsReset}},
	0x38: Opcode{0x38, true, "SRL B", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x39: Opcode{0x39, true, "SRL C", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x3a: Opcode{0x3a, true, "SRL D", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x3b: Opcode{0x3b, true, "SRL E", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x3c: Opcode{0x3c, true, "SRL H", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x3d: Opcode{0x3d, true, "SRL L", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x3e: Opcode{0x3e, true, "SRL (HL)", 2, 16, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x3f: Opcode{0x3f, true, "SRL A", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x04: Opcode{0x04, true, "RLC H", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x40: Opcode{0x40, true, "BIT 0, B", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x41: Opcode{0x41, true, "BIT 0, C", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x42: Opcode{0x42, true, "BIT 0, D", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x43: Opcode{0x43, true, "BIT 0, E", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x44: Opcode{0x44, true, "BIT 0, H", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x45: Opcode{0x45, true, "BIT 0, L", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x46: Opcode{0x46, true, "BIT 0, (HL)", 2, 16, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x47: Opcode{0x47, true, "BIT 0, A", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x48: Opcode{0x48, true, "BIT 1, B", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x49: Opcode{0x49, true, "BIT 1, C", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x4a: Opcode{0x4a, true, "BIT 1, D", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x4b: Opcode{0x4b, true, "BIT 1, E", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x4c: Opcode{0x4c, true, "BIT 1, H", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x4d: Opcode{0x4d, true, "BIT 1, L", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x4e: Opcode{0x4e, true, "BIT 1, (HL)", 2, 16, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x4f: Opcode{0x4f, true, "BIT 1, A", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x05: Opcode{0x05, true, "RLC L", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x50: Opcode{0x50, true, "BIT 2, B", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x51: Opcode{0x51, true, "BIT 2, C", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x52: Opcode{0x52, true, "BIT 2, D", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x53: Opcode{0x53, true, "BIT 2, E", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x54: Opcode{0x54, true, "BIT 2, H", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x55: Opcode{0x55, true, "BIT 2, L", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x56: Opcode{0x56, true, "BIT 2, (HL)", 2, 16, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x57: Opcode{0x57, true, "BIT 2, A", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x58: Opcode{0x58, true, "BIT 3, B", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x59: Opcode{0x59, true, "BIT 3, C", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x5a: Opcode{0x5a, true, "BIT 3, D", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x5b: Opcode{0x5b, true, "BIT 3, E", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x5c: Opcode{0x5c, true, "BIT 3, H", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x5d: Opcode{0x5d, true, "BIT 3, L", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x5e: Opcode{0x5e, true, "BIT 3, (HL)", 2, 16, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x5f: Opcode{0x5f, true, "BIT 3, A", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x06: Opcode{0x06, true, "RLC (HL)", 2, 16, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x60: Opcode{0x60, true, "BIT 4, B", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x61: Opcode{0x61, true, "BIT 4, C", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x62: Opcode{0x62, true, "BIT 4, D", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x63: Opcode{0x63, true, "BIT 4, E", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x64: Opcode{0x64, true, "BIT 4, H", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x65: Opcode{0x65, true, "BIT 4, L", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x66: Opcode{0x66, true, "BIT 4, (HL)", 2, 16, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x67: Opcode{0x67, true, "BIT 4, A", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x68: Opcode{0x68, true, "BIT 5, B", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x69: Opcode{0x69, true, "BIT 5, C", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x6a: Opcode{0x6a, true, "BIT 5, D", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x6b: Opcode{0x6b, true, "BIT 5, E", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x6c: Opcode{0x6c, true, "BIT 5, H", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x6d: Opcode{0x6d, true, "BIT 5, L", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x6e: Opcode{0x6e, true, "BIT 5, (HL)", 2, 16, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x6f: Opcode{0x6f, true, "BIT 5, A", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x07: Opcode{0x07, true, "RLC A", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x70: Opcode{0x70, true, "BIT 6, B", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x71: Opcode{0x71, true, "BIT 6, C", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x72: Opcode{0x72, true, "BIT 6, D", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x73: Opcode{0x73, true, "BIT 6, E", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x74: Opcode{0x74, true, "BIT 6, H", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x75: Opcode{0x75, true, "BIT 6, L", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x76: Opcode{0x76, true, "BIT 6, (HL)", 2, 16, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x77: Opcode{0x77, true, "BIT 6, A", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x78: Opcode{0x78, true, "BIT 7, B", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x79: Opcode{0x79, true, "BIT 7, C", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x7a: Opcode{0x7a, true, "BIT 7, D", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x7b: Opcode{0x7b, true, "BIT 7, E", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x7c: Opcode{0x7c, true, "BIT 7, H", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x7d: Opcode{0x7d, true, "BIT 7, L", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x7e: Opcode{0x7e, true, "BIT 7, (HL)", 2, 16, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x7f: Opcode{0x7f, true, "BIT 7, A", 2, 8, 0, Flags{CanChange, IsReset, IsSet, NoChange}},
	0x08: Opcode{0x08, true, "RRC B", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x80: Opcode{0x80, true, "RES 0, B", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x81: Opcode{0x81, true, "RES 0, C", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x82: Opcode{0x82, true, "RES 0, D", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x83: Opcode{0x83, true, "RES 0, E", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x84: Opcode{0x84, true, "RES 0, H", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x85: Opcode{0x85, true, "RES 0, L", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x86: Opcode{0x86, true, "RES 0, (HL)", 2, 16, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x87: Opcode{0x87, true, "RES 0, A", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x88: Opcode{0x88, true, "RES 1, B", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x89: Opcode{0x89, true, "RES 1, C", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x8a: Opcode{0x8a, true, "RES 1, D", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x8b: Opcode{0x8b, true, "RES 1, E", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x8c: Opcode{0x8c, true, "RES 1, H", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x8d: Opcode{0x8d, true, "RES 1, L", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x8e: Opcode{0x8e, true, "RES 1, (HL)", 2, 16, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x8f: Opcode{0x8f, true, "RES 1, A", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x09: Opcode{0x09, true, "RRC C", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0x90: Opcode{0x90, true, "RES 2, B", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x91: Opcode{0x91, true, "RES 2, C", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x92: Opcode{0x92, true, "RES 2, D", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x93: Opcode{0x93, true, "RES 2, E", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x94: Opcode{0x94, true, "RES 2, H", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x95: Opcode{0x95, true, "RES 2, L", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x96: Opcode{0x96, true, "RES 2, (HL)", 2, 16, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x97: Opcode{0x97, true, "RES 2, A", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x98: Opcode{0x98, true, "RES 3, B", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x99: Opcode{0x99, true, "RES 3, C", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x9a: Opcode{0x9a, true, "RES 3, D", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x9b: Opcode{0x9b, true, "RES 3, E", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x9c: Opcode{0x9c, true, "RES 3, H", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x9d: Opcode{0x9d, true, "RES 3, L", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x9e: Opcode{0x9e, true, "RES 3, (HL)", 2, 16, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x9f: Opcode{0x9f, true, "RES 3, A", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x0a: Opcode{0x0a, true, "RRC D", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0xa0: Opcode{0xa0, true, "RES 4, B", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xa1: Opcode{0xa1, true, "RES 4, C", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xa2: Opcode{0xa2, true, "RES 4, D", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xa3: Opcode{0xa3, true, "RES 4, E", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xa4: Opcode{0xa4, true, "RES 4, H", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xa5: Opcode{0xa5, true, "RES 4, L", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xa6: Opcode{0xa6, true, "RES 4, (HL)", 2, 16, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xa7: Opcode{0xa7, true, "RES 4, A", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xa8: Opcode{0xa8, true, "RES 5, B", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xa9: Opcode{0xa9, true, "RES 5, C", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xaa: Opcode{0xaa, true, "RES 5, D", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xab: Opcode{0xab, true, "RES 5, E", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xac: Opcode{0xac, true, "RES 5, H", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xad: Opcode{0xad, true, "RES 5, L", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xae: Opcode{0xae, true, "RES 5, (HL)", 2, 16, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xaf: Opcode{0xaf, true, "RES 5, A", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x0b: Opcode{0x0b, true, "RRC E", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0xb0: Opcode{0xb0, true, "RES 6, B", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xb1: Opcode{0xb1, true, "RES 6, C", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xb2: Opcode{0xb2, true, "RES 6, D", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xb3: Opcode{0xb3, true, "RES 6, E", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xb4: Opcode{0xb4, true, "RES 6, H", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xb5: Opcode{0xb5, true, "RES 6, L", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xb6: Opcode{0xb6, true, "RES 6, (HL)", 2, 16, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xb7: Opcode{0xb7, true, "RES 6, A", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xb8: Opcode{0xb8, true, "RES 7, B", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xb9: Opcode{0xb9, true, "RES 7, C", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xba: Opcode{0xba, true, "RES 7, D", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xbb: Opcode{0xbb, true, "RES 7, E", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xbc: Opcode{0xbc, true, "RES 7, H", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xbd: Opcode{0xbd, true, "RES 7, L", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xbe: Opcode{0xbe, true, "RES 7, (HL)", 2, 16, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xbf: Opcode{0xbf, true, "RES 7, A", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x0c: Opcode{0x0c, true, "RRC H", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0xc0: Opcode{0xc0, true, "SET 0, B", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xc1: Opcode{0xc1, true, "SET 0, C", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xc2: Opcode{0xc2, true, "SET 0, D", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xc3: Opcode{0xc3, true, "SET 0, E", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xc4: Opcode{0xc4, true, "SET 0, H", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xc5: Opcode{0xc5, true, "SET 0, L", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xc6: Opcode{0xc6, true, "SET 0, (HL)", 2, 16, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xc7: Opcode{0xc7, true, "SET 0, A", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xc8: Opcode{0xc8, true, "SET 1, B", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xc9: Opcode{0xc9, true, "SET 1, C", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xca: Opcode{0xca, true, "SET 1, D", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xcb: Opcode{0xcb, true, "SET 1, E", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xcc: Opcode{0xcc, true, "SET 1, H", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xcd: Opcode{0xcd, true, "SET 1, L", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xce: Opcode{0xce, true, "SET 1, (HL)", 2, 16, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xcf: Opcode{0xcf, true, "SET 1, A", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x0d: Opcode{0x0d, true, "RRC L", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0xd0: Opcode{0xd0, true, "SET 2, B", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xd1: Opcode{0xd1, true, "SET 2, C", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xd2: Opcode{0xd2, true, "SET 2, D", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xd3: Opcode{0xd3, true, "SET 2, E", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xd4: Opcode{0xd4, true, "SET 2, H", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xd5: Opcode{0xd5, true, "SET 2, L", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xd6: Opcode{0xd6, true, "SET 2, (HL)", 2, 16, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xd7: Opcode{0xd7, true, "SET 2, A", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xd8: Opcode{0xd8, true, "SET 3, B", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xd9: Opcode{0xd9, true, "SET 3, C", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xda: Opcode{0xda, true, "SET 3, D", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xdb: Opcode{0xdb, true, "SET 3, E", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xdc: Opcode{0xdc, true, "SET 3, H", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xdd: Opcode{0xdd, true, "SET 3, L", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xde: Opcode{0xde, true, "SET 3, (HL)", 2, 16, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xdf: Opcode{0xdf, true, "SET 3, A", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x0e: Opcode{0x0e, true, "RRC (HL)", 2, 16, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0xe0: Opcode{0xe0, true, "SET 4, B", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xe1: Opcode{0xe1, true, "SET 4, C", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xe2: Opcode{0xe2, true, "SET 4, D", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xe3: Opcode{0xe3, true, "SET 4, E", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xe4: Opcode{0xe4, true, "SET 4, H", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xe5: Opcode{0xe5, true, "SET 4, L", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xe6: Opcode{0xe6, true, "SET 4, (HL)", 2, 16, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xe7: Opcode{0xe7, true, "SET 4, A", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xe8: Opcode{0xe8, true, "SET 5, B", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xe9: Opcode{0xe9, true, "SET 5, C", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xea: Opcode{0xea, true, "SET 5, D", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xeb: Opcode{0xeb, true, "SET 5, E", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xec: Opcode{0xec, true, "SET 5, H", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xed: Opcode{0xed, true, "SET 5, L", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xee: Opcode{0xee, true, "SET 5, (HL)", 2, 16, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xef: Opcode{0xef, true, "SET 5, A", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0x0f: Opcode{0x0f, true, "RRC A", 2, 8, 0, Flags{CanChange, IsReset, IsReset, CanChange}},
	0xf0: Opcode{0xf0, true, "SET 6, B", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xf1: Opcode{0xf1, true, "SET 6, C", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xf2: Opcode{0xf2, true, "SET 6, D", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xf3: Opcode{0xf3, true, "SET 6, E", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xf4: Opcode{0xf4, true, "SET 6, H", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xf5: Opcode{0xf5, true, "SET 6, L", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xf6: Opcode{0xf6, true, "SET 6, (HL)", 2, 16, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xf7: Opcode{0xf7, true, "SET 6, A", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xf8: Opcode{0xf8, true, "SET 7, B", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xf9: Opcode{0xf9, true, "SET 7, C", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xfa: Opcode{0xfa, true, "SET 7, D", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xfb: Opcode{0xfb, true, "SET 7, E", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xfc: Opcode{0xfc, true, "SET 7, H", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xfd: Opcode{0xfd, true, "SET 7, L", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xfe: Opcode{0xfe, true, "SET 7, (HL)", 2, 16, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
	0xff: Opcode{0xff, true, "SET 7, A", 2, 8, 0, Flags{NoChange, NoChange, NoChange, NoChange}},
}
